// <auto-generated />
namespace vezba_lab3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class someTouches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(someTouches));
        
        string IMigrationMetadata.Id
        {
            get { return "202405230001210_someTouches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
