// <auto-generated />
namespace vezba_lab3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class superfinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(superfinal));
        
        string IMigrationMetadata.Id
        {
            get { return "202405170735391_super-final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
